### JSF CONFIGS ###
server:
  context_parameters:
    com:
      sun:
        faces:
          forceLoadConfiguration: true

### H2 ###
spring:
  datasource:
    url: jdbc:h2:file:./data/productdb # Persistente Datenbank in Datei, ohne /data/ speeichern sich Usern nicht
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # Behalte bestehendes Schema und Daten
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false    # SQL-Statements formatiert ausgeben

  h2:
    console:
      enabled: true # Aktiviert H2-Konsole
      path: /h2-console # Standardpfad zur Konsole

logging:
  level:
    root: WARN
    org:
      springframework: WARN
      hibernate: WARN
      hibernate.type: OFF
      hibernate.SQL: OFF
    javax.faces: WARN
